---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Custom-Properties-Delete-Dialog

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: userEmail
          operator: in-array
          operands:
            - 1234@abc.com
    flagValue: false
