---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Target-Groups-Delete-Dialog

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: QA-team
    flagValue: false
